---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-proxy-config
data:
  sites.whitelist.txt: |-
    .githubusercontent.com
    .github.com
    .cluster.local
  squid.conf: |-
    always_direct allow all

    acl localhost src 127.0.0.1/32
    acl to_localhost dst 127.0.0.0/8
    acl localnet src 10.0.0.0/8 # RFC1918 possible internal network
    acl localnet src 172.16.0.0/12  # RFC1918 possible internal network
    acl localnet src 192.168.0.0/16 # RFC1918 possible internal network
    acl SSL_ports port 443
    acl Safe_ports port 80    # http
    acl Safe_ports port 21    # ftp
    acl Safe_ports port 443   # https
    acl Safe_ports port 70    # gopher
    acl Safe_ports port 210   # wais
    acl Safe_ports port 1025-65535  # unregistered ports
    acl Safe_ports port 280   # http-mgmt
    acl Safe_ports port 488   # gss-http
    acl Safe_ports port 591   # filemaker
    acl Safe_ports port 777   # multiling http
    acl CONNECT method CONNECT

    # Deny requests to unsafe ports
    http_access deny !Safe_ports
    # Deny CONNECT to other thatn secure SSL ports
    # http_access deny CONNECT !SSL_ports

    # only allow cachemgr access from localhost
    http_access allow localhost manager
    http_access deny manager

    #
    # INSERT YOUR OWN RULE(S) HERE TO ALLOW ACCESS FROM YOUR CLIENTS
    #
    acl whitelist dstdomain "/etc/squid/sites.whitelist.txt"
    http_access allow whitelist

    # And finally deny all other access to this proxy
    http_access deny all

    http_port 3128

    # Disable cache to avoid unexpected behaviors
    cache_dir null /tmp
    cache deny all

    access_log /var/log/squid/access.log squid
    cache_log /var/log/squid/cache.log squid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy
spec:
  selector:
    matchLabels:
      app: squid
      type: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: squid
        type: proxy
    spec:
      containers:
      - name: squid
        image: ubuntu/squid:5.6-22.10_edge # latest
        ports:
        - containerPort: 3128
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/squid/squid.conf
          subPath: squid.conf
          name: squid-conf
        - mountPath: /etc/squid/sites.whitelist.txt
          subPath: sites.whitelist.txt
          name: squid-conf
      volumes:
      - name: squid-conf
        configMap:
          name: squid-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: squid
    type: proxy
  name: squid-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    app: squid
    type: proxy